name: Continuous Integration
on: [push]

jobs:
  build:
    name: Test
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Run Cargo Tests
        run: cargo test --all-features
