name: Continuous Integration
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Run Cargo Tests
        run: cargo test --all-features
