name: "Continuous Integration"
on: [push]

jobs:
  test:
    name: "Test"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-node@v1"
      - name: "Perform Setup"
        run: "make setup"
      - name: "Run Tests"
        run: "make test"
